services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "9090:9090"

    environment:
      - SERVER_PORT=9090
      - SPRING_PROFILES_ACTIVE=${PROFILE_SPRING}

      - URL_BD_GATEWAY=${URL_BD_GATEWAY}
      - USER_NAME_BD=${USER_NAME_BD}
      - PASSWORD_BD=${PASSWORD_BD}

      - URL_BD_GATEWAY_JDBC=${URL_BD_GATEWAY_JDBC}

      # Seguridad
      - ISSUER_URI_KEYCLOAK=${ISSUER_URI_KEYCLOAK}
      - JWK_SET_URI_KEYCLOAK=${JWK_SET_URI_KEYCLOAK}

      # Rutas
      - URI_PADRON=${URI_PADRON}
      - URI_CALCULO=${URI_CALCULO}

      - EUREKA_URI=${EUREKA_URI}

    networks:
      - siim-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  siim-network:
    name: siim-global-net
    external: true