server:
  port: 9090

spring:
  application:
    name: api-gateway

    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true # Permite usar /ms-padron-unico en vez de /MS-PADRON-UNICO

  # SEGURIDAD
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI_KEYCLOAK:http://localhost:8180/realms/tuxtepec-gob}
          jwk-set-uri: ${JWK_SET_URI_KEYCLOAK:http://keycloak:8180/realms/tuxtepec-gob/protocol/openid-connect/certs}

  cloud:
    gateway:
      server:
        webflux:
          # CORS GLOBAL
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

          # RUTAS
          routes:
            # MS-PADRON
            - id: padron-route
              uri: ${URI_PADRON:http://ms-padron-app:8080}
              predicates:
                - Path=/api/v1/sujetos-pasivos/**, /api/v1/predios/**, /api/v1/licencias/**

            # MS-CALCULO
            - id: calculo-impuestos
              uri: ${URI_CALCULO:http://ms-calculo-app:8080}
              predicates:
                - Path=/api/v1/calculos/**

eureka:
  client:
    service-url:
      defaultZone: ${URL_EUREKA:http://localhost:8761/eureka/}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO

